name: Build and deploy to gh-pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Set up TeXLive
        uses: zauguin/install-texlive@v4
        with:
          packages: scheme-basic latexmk float

      - name: Build
        run: ./build.sh

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: gh-pages
